/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#0c1018',
        nebula: '#f5efe6',
        aurora: '#2dd4bf',
        flare: '#ff6b4a',
        magneto: '#1e2538',
        sand: '#f2c94c',
        sky: '#5ab0ff',
        'surface-container-highest': '#2f3638',
        'on-secondary-container': '#00311f',
        'on-primary-container': '#005763',
        'surface-container-high': '#242b2d',
        'on-error': '#690005',
        'surface-container-lowest': '#090f11',
        'surface-dim': '#0e1416',
        'tertiary-fixed': '#ffddb8',
        'on-primary': '#00363e',
        'outline-variant': '#3c494c',
        'on-background': '#dde4e5',
        'primary-fixed': '#a2eeff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-primary-fixed': '#001f25',
        tertiary: '#ffd6a7',
        'inverse-primary': '#006877',
        'surface-container-low': '#161d1e',
        outline: '#859397',
        'inverse-on-surface': '#2b3233',
        'on-secondary-fixed': '#002113',
        'surface-variant': '#2f3638',
        background: '#0e1416',
        'on-error-container': '#ffdad6',
        surface: '#0e1416',
        'error-container': '#93000a',
        'primary-fixed-dim': '#2fd9f4',
        'on-primary-fixed-variant': '#004e5a',
        'on-tertiary': '#472a00',
        error: '#ffb4ab',
        secondary: '#4edea3',
        primary: '#8aebff',
        'on-surface': '#dde4e5',
        'secondary-fixed-dim': '#4edea3',
        'surface-container': '#1a2122',
        'surface-bright': '#343a3c',
        'inverse-surface': '#dde4e5',
        'secondary-container': '#00a572',
        'on-surface-variant': '#bbc9cd',
        'tertiary-container': '#ffb147',
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#2a1700',
        'surface-tint': '#2fd9f4',
        'on-tertiary-container': '#704500',
        'secondary-fixed': '#6ffbbe',
        'primary-container': '#22d3ee',
        'on-secondary': '#003824',
      },
      fontFamily: {
        display: ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', '"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'mono-data': ['"IBM Plex Mono"', '"JetBrains Mono"', 'ui-monospace', 'monospace'],
        h1: ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        h2: ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        h3: ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        label: ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        'body-lg': ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        'body-md': ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
        'body-sm': ['"Space Grotesk"', '"Eurostile"', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        glow: '0 0 40px rgba(45, 212, 191, 0.25)',
      },
      backgroundImage: {
        'starlight': 'radial-gradient(circle at 10% 20%, rgba(45, 212, 191, 0.22), transparent 38%), radial-gradient(circle at 85% 5%, rgba(255, 107, 74, 0.2), transparent 42%), linear-gradient(145deg, rgba(8, 12, 18, 0.96), rgba(15, 20, 34, 0.98))',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        'bento-gap': '16px',
        lg: '24px',
        xs: '4px',
        sm: '8px',
        unit: '4px',
        xl: '32px',
        'container-margin': '40px',
      },
      fontSize: {
        'mono-data': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        h1: ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        h3: ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        label: ['11px', { lineHeight: '1', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
